/* Sample Exercise 2

   A triangular number can also be generated by the formula

   Triangular number = n (n + 1) / 2

   for any integer value n.  Write a program to generate every
   fifth triangular number between 5 and 50 (5, 10, 15 ... 50)

   Hint:  Good place to use a loop ... increment each time  by 5

*/

#include <stdio.h>

int main(void) {

  int n, triangularNumber;

  printf("TABLE OF TRIANGULATED NUMBERS\n\n");
  printf(" n     Sum from 1 to n\n");
  printf("----   ---------------\n");

  triangularNumber = 0;

  for ( n = 1; n <= 10; n = n + 1) {
    
    triangularNumber = n * 5;
    
      printf("%2i      %i\n", n, triangularNumber);
  }
    

  return 0;
}
